name: Build production Docker image

on:
  #push:
    #branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      #- uses: actions/setup-node@v2
        #with:
          #node-version: 14.15.5

      #- run: npm ci
      #- run: npm run build

      - uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker registry on GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase author and repository name
        run: echo "REPO_LOWERCASE=ghcr.io/scriptychris/fake-pev-shopping" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REPO_LOWERCASE }}
