name: Integrate

on:
  issues:
  #pull_request:
    branches: [ develop ]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.5

      - run: npm ci
      - run: npm test
